#!/bin/bash

source /home/admin/lib/cli
source /home/admin/lib/cli-web

lbdir=/home/admin/root/lb

getquery
action=$( get_parameter $query "action" )
vipname=$( get_parameter $query "vipname" )

case $action in
  "newvip")
    sudo /usr/local/sbin/remountrw
    mkdir $lbdir/frontend_$vipname
    echo "bind*=*:80" > $lbdir/frontend_$vipname/bind
    echo "mode*=http" > $lbdir/frontend_$vipname/mode
    echo "log*=global" > $lbdir/frontend_$vipname/log
    sudo /usr/local/sbin/remountro
  ;;
  "deletebackend")
     srvid=$( get_parameter $query "srvid" )
     sudo /usr/local/sbin/remountrw
     rm $lbdir/frontend_$vipname/server_$srvid
     sudo /usr/local/sbin/remountro
  ;;
  "delusebe")
     id=$( get_parameter $query "id" )
     sudo /usr/local/sbin/remountrw
     if [ "$id" = "default" ]; then
       rm $lbdir/frontend_$vipname/default_backend_0
     else
       rm $lbdir/frontend_$vipname/use_backend_$id
     fi
     sudo /usr/local/sbin/remountro
  ;;
  "configbind")
     bind=$( get_parameter $query "bind" )
     sudo /usr/local/sbin/remountrw
     echo "bind*=$bind" > $lbdir/frontend_$vipname/bind
     sudo /usr/local/sbin/remountro
  ;;
  "configmode")
     mode=$( get_parameter $query "mode" )
     sudo /usr/local/sbin/remountrw
     echo "mode*=$mode" > $lbdir/frontend_$vipname/mode
     sudo /usr/local/sbin/remountro
  ;;
  delacl)
    aclname=$( get_parameter $query "aclname" )
    aclline=$( get_parameter $query "line" )
    sudo /usr/local/sbin/remountrw
    eval sed -i \'${aclline}d\' $lbdir/frontend_$vipname/acl_$aclname
    aclline=$(wc -l $lbdir/frontend_$vipname/acl_$aclname | awk '{print$1}')
    [ "$aclline" = "0" ] && rm $lbdir/frontend_$vipname/acl_$aclname
    sudo /usr/local/sbin/remountro
  ;;
  setbe)
    backend=$( get_parameter $query "backend" )
    backend_acl=$( get_parameter $query "backend_acl" )
    fe_be_condition=$( get_parameter $query "fe_be_condition" )
  
    if [ "$fe_be_condition" = "default" ] ; then
      sudo /usr/local/sbin/remountrw
      echo "default_backend*=$backend" > $lbdir/frontend_$vipname/default_backend_0
      sudo /usr/local/sbin/remountro
    else
      lastId=$(ls $lbdir/frontend_$vipname/use_backend_* 2>/dev/null | sed 's/^.*_//' | sort -g  | tail -1)
      if [ -z $lastId ] ; then
        id=0
      else
        id=$(($lastId + 1))
      fi 
      sudo /usr/local/sbin/remountrw
      echo "backend*=$backend"  > $lbdir/frontend_$vipname/use_backend_$id 
      echo "condition*=$fe_be_condition"  >> $lbdir/frontend_$vipname/use_backend_$id 
      echo "acl*=$backend_acl"  >> $lbdir/frontend_$vipname/use_backend_$id 
      sudo /usr/local/sbin/remountro
    fi
  ;;
  "newredirect")
    redirectname=$( get_parameter $query "redirectname" )
    type=$( get_parameter $query "type" )
    to=$( get_parameter $query "to" )
    code=$( get_parameter $query "code" )
    [ "$code" = "" ] && code="302"
    option=$( get_parameter $query "option" )
    cond=$( get_parameter $query "cond" )
    acl=$( get_parameter $query "redirect_acl" )
    sudo /usr/local/sbin/remountrw
    echo "redirect*=$type $to code $code $option $cond $acl" > $lbdir/frontend_$vipname/redirect_$redirectname 
    sudo /usr/local/sbin/remountro
  ;;
  "delredirect")
    redirectname=$( get_parameter $query "redirectname" )
    sudo /usr/local/sbin/remountrw
    rm $lbdir/frontend_$vipname/redirect_$redirectname
    sudo /usr/local/sbin/remountro
  ;;
  newacl)
    aclname=$( get_parameter $query "aclname" )
    aclcriterion=$( get_parameter $query "aclcriterion" )
    aclflag=$( get_parameter $query "aclflag" )
    acloperator=$( get_parameter $query "acloperator" )
    aclvalues=$( get_parameter $query "aclvalues" )
  
    sudo /usr/local/sbin/remountrw
    if [ -f $lbdir/frontend_$vipname/acl_$aclname ] ; then
      echo "$aclname=$aclcriterion $aclflag $acloperator $aclvalues" >> $lbdir/frontend_$vipname/acl_$aclname
    else
      echo "$aclname=$aclcriterion $aclflag $acloperator $aclvalues" > $lbdir/frontend_$vipname/acl_$aclname
    fi
    sudo /usr/local/sbin/remountro
  ;;
  "doc_acl")
    DOCacl="1";
  ;;
esac

totsession=$(printf "show stat \n " | /home/admin/bin/socat - /tmp/lb.socket  | grep $vipname | grep FRONTEND | cut -d ',' -f '8')

cat $templatedir/header.template
echo  "
<h2>UaR vip $vipname ( $totsession session managed ) </h2>
<a href=\"/lb-hp\">lb homepage</a>
<a href=\"/lb-hp?action=delvip&vipname=$vipname\">Delete Vip</a>
<a href=\"/vip?vipname=$vipname\">Refresh Vip</a>
<table border=\"1\">
"

value=$(getValue $lbdir/frontend_$vipname/bind 'bind\*')
#echo "<p>getValue $lbdir/frontend_$vipname/bind bind</p>"
echo "<form action=\"/vip\" method=\"get\">
<input type=\"hidden\" name=\"action\" value=\"configbind\" />
<input type=\"hidden\" name=\"vipname\" value=\"$vipname\" />
<tr><td>bind</td><td><input type=\"text\" name=\"bind\" value=\"$value\" /></td><td><input type=\"submit\" /></td></tr>
</form>"

_mode=$(getValue $lbdir/frontend_$vipname/mode 'mode\*')
echo "
<form action=\"/vip\" method=\"get\">
<input type=\"hidden\" name=\"action\" value=\"configmode\" />
<input type=\"hidden\" name=\"vipname\" value=\"$vipname\" />
<tr><td>mode</td><td><select name=\"mode\" >
 <option value=\"$mode\"> $_mode </option> 
 <option value=\"http\"> http </option> 
 <option value=\"tcp\">  tcp </option>
</select></td><td><input type=\"submit\" /></td></tr>
</form>"

echo "</table>"

echo "<h1>Connect to backends </h1>"
echo "<table border=\"1\">
<tr><th>backend</th><th>condition</th><th>acl</th><th>action</th></tr>
"
for file in $lbdir/frontend_$vipname/use_backend_*; do 
  id=$(basename $file)
  id=${id##*_}
  [ "$id" = "*" ] && break
  bck=$(grep backend $file | cut -d '=' -f 2)
  con=$(grep condition $file | cut -d '=' -f 2)
  acl=$(grep acl $file | cut -d '=' -f 2)
  echo "<tr><td>$bck</td><td>$con</td><td>$acl</td><td><a href=\"vip?vipname=$vipname&action=delusebe&id=$id\" >delete</a></td></tr>"
done
  file="$lbdir/frontend_$vipname/default_backend_0"
  if [ -r $file ]; then
    bck=$(grep default_backend $file | cut -d '=' -f 2)
    con="default"
    acl="-"
    echo "<tr><td>$bck</td><td>$con</td><td>$acl</td><td><a href=\"vip?vipname=$vipname&action=delusebe&id=default\" >delete</a></td></tr>"
  fi
echo "</table>
<p>
"

numbe=$(ls $lbdir/backend_* | wc -l)
if [ "$numbe" = "0" ]; then
  echo "no backends available"
else
  echo "<form action=\"vip\" method=\"get\">
  <input type=\"hidden\" name=\"action\" value=\"setbe\" />
  <input type=\"hidden\" name=\"vipname\" value=\"$vipname\" />
  <select name=\"backend\" >"
  for file in $lbdir/backend_*; do
    id=${file##*_}
    echo "<option value=\"$id\"> $id </option>"
  done
  echo "</select>"
  echo "<select name=\"fe_be_condition\" >
    <option value=\"if\"> if </option>
    <option value=\"unless\"> unless </option>
    <option value=\"default\"> default </option>
  </select>
  <input type=\"text\" name=\"backend_acl\" />
  <input type=\"submit\" value=\"use backend\" />
  </form>
</p>
  "
fi
echo "
<p>
  <form action=\"/backend\" method=\"get\">
    <input type=\"hidden\" name=\"action\" value=\"newbackend\" />
    <input type=\"text\" name=\"backendname\" />
    <input type=\"submit\" value=\"new backend\"/>
  </form>
</p>
"

echo "<h1>Redirect</h1>"
numredirect=$(ls $lbdir/frontend_$vipname/redirect_* | wc -l)
if [ "$numredirect" = "0" ]; then
  echo "no redirect available"
else
echo "<table border=\"1\">
<table><tr><th>name</th><th>redirect</th></tr>"
for file in $lbdir/frontend_$vipname/redirect_*; do 
 redirectname=$(basename $file)
 redirectname=${redirectname#*_}
 num=1
 echo "<tr><th>$redirectname</th><td>$(getValue $file "redirect\*")</td><td><a href=\"vip?vipname=$vipname&action=delredirect&redirectname=$redirectname\">delete</a></td></tr>"
done
echo " </table>"  
fi
  echo "<form action=\"vip\" method=\"get\">
  <input type=\"hidden\" name=\"action\" value=\"newredirect\" />
  <input type=\"hidden\" name=\"vipname\" value=\"$vipname\" />
  <table><tr><th>name</th><th>type</th><th>to</th><th>code</th><th>option</th><th>condition</th><th>acl</th><th>action</th></tr>
  <tr><td>
  <input type=\"text\" name=\"redirectname\" />
  </td><td>
  <select name=\"type\" >
    <option value=\"prefix\"> prefix </option>
    <option value=\"location\"> location  </option>
    </select>
  </td><td>
  <input type=\"text\" name=\"to\" />
  </td><td>
    <select name=\"code\" >
    <option value=\"302\"> 302 (moved temporary) </option>
    <option value=\"301\"> 301 (moved permanently) </option>
    <option value=\"303\"> 303 (like 302 with get) </option>
  </select>
  </td><td>
  <select name=\"option\" >
    <option value=\"\"> </option>
    <option value=\"drop-query\"> drop-query </option>
  </select>
  </td><td>
  <select name=\"cond\" >
    <option value=\"if\"> if </option>
    <option value=\"unless\"> unless </option>
  </select>
  </td><td>
  <input type=\"text\" name=\"redirect_acl\" />
  </td><td>
  <input type=\"submit\" />
  </td><tr></table>
  </form>
</p>
  "
echo "<h1>ACL</h1>"
numacl=$(ls $lbdir/frontend_$vipname/acl_* | wc -l)
echo "<table border=\"1\">
<tr><th>Name</th><th>acl</th><th>action</th><th><a href=\"vip?vipname=$vipname&action=doc_acl\">Help</a></th></tr>"
for file in $lbdir/frontend_$vipname/acl_*; do 
 aclname=$(basename $file)
 aclname=${aclname#*_}
 num=1
 cat $file | while read line; do 
   _line=$(echo $line | sed "s/${aclname}=//" )
   echo "<tr><th>$aclname</th><td>$_line</td><td><a href=\"vip?vipname=$vipname&action=delacl&aclname=$aclname&line=$num\">delete</a></td></tr>"
   num=$(( $num + 1 ))
 done 
done
echo " </table>"


echo "<br/>
<table style=\"text-align: center\">
<tr><th>Name</th><th>criterion</th><th>flags</th><th>operator</th><th>values</th><th></th></tr>
<tr><td>url_static</td><td>path_end</td><td> </td><td></td><td>.css .js .jpg .gif .png</td><th><- example</th></tr>
<tr><td>host_www</td><td>hdr_beg(host)</td><td>-i</td><td></td><td>www</td><th><- example</th></tr>
<form action=\"vip\" method=\"get\">
<input type=\"hidden\" name=\"vipname\" value=\"$vipname\" />
<input type=\"hidden\" name=\"action\" value=\"newacl\" />
<tr>
  <td><input type=\"text\" name=\"aclname\" /></td>
  <td><input type=\"text\" name=\"aclcriterion\" /></td>
  <td>
    <select name=\"aclflag\">
      <option value=\"\"> </option>
      <option value=\"-i\"> case insensitive </option>
      <option value=\"--\"> end flags </option>
    </select>
  </td>
  <td>
    <select name=\"acloperator\">
      <option value=\"\"> </option>
      <option value=\"eq\"> = </option>
      <option value=\"ge\"> >= </option>
      <option value=\"gt\"> > </option>
      <option value=\"le\"> <= </option>
      <option value=\"lt\"> < </option>
    </select>
  </td>
  <td><input type=\"text\" name=\"aclvalues\" /></td>
  <td><input type=\"submit\" /></td>
</tr></form>
</table>"

[ "$DOCacl" = "1" ] && cat doc_acl

cat $templatedir/footer.template
